/**
 * Generated Design Tokens from tokens.json.
 * DO NOT EDIT DIRECTLY. Generated by packages/design-system/scripts/generate-tokens.js
 */

export const GENERATED_TOKENS = {
  color: {
    status: {
      online: "#4CAF50",
      offline: "#F44336",
      degraded: "#FF9800",
      unknown: "#9E9E9E",
      success: "#7CFFD8",
      warning: "#FFD56D",
      unsaved: "#FF9800",
    },
    editor: {
      appbarBackground: "#252526",
      background: "#1E1E1E",
      panelBackground: "#2D2D2D",
      divider: "#3C3C3C",
      text: "#D4D4D4",
      textMuted: "#B0B0B0",
      textDim: "#808080",
    },
    scene: {
      background: "#000000",
      shadow: "#00000088",
    },
    aurora: {
      color1: "#6DE8FF38",
      color2: "#8C7CFF38",
      color3: "#7CFFD828",
    },
    glass: {
      background: "#101C338C",
      stroke: "#FFFFFF14",
    },
    coordColor: "#B5C7E9",
    onSurfaceDim: "#B5C7E9",
    outlineSubtle: "#334364",
    unreadBadge: "#6DE8FF",
    onUnreadBadge: "#03212A",
    hudBackground: "#000000AA",
    hudStroke: "#FFFFFF33",
  },
} as const;

export type GeneratedTokens = typeof GENERATED_TOKENS;
