/**
 * Removal of data that was generated by the viewer instead of received from a
 * grid or entered by the resident.
 *
 * Earlier builds seeded invented conversations (made-up residents, "seed-"
 * message ids) into the real saved chat history. New code never creates such
 * data, but installs that already ran those builds still have it stored, so it
 * is purged automatically at startup. Matching uses the placeholder ids the old
 * code assigned and the "seed-" id prefix, never display names: a genuine
 * resident who happens to share a name is left alone.
 *
 * `npm run check:fake-data` is the other half: it keeps this kind of data from
 * being written into the source in the first place.
 */
import { Utils } from './utils';

/** Placeholder agent ids the old seeding code gave its invented residents. */
export const FABRICATED_CONTACT_IDS: ReadonlySet<string> = new Set([
  'nyx-uuid',
  'kit-uuid',
  'sable-uuid',
  'ruth-uuid',
]);

export const STORAGE_KEYS = {
  chatHistory: 'linkpoint_chat_history',
  openSessions: 'linkpoint_open_im_sessions',
} as const;

export function isFabricatedContact(contactId: unknown, _contactName?: unknown): boolean {
  return typeof contactId === 'string' && FABRICATED_CONTACT_IDS.has(contactId);
}

/** Remove messages that were generated by the viewer rather than received or sent. */
export function purgeFabricatedMessages<
  T extends { id?: unknown; senderId?: unknown; recipientId?: unknown },
>(messages: T[]) {
  const kept = messages.filter(
    (m) =>
      !(
        m &&
        ((typeof m.id === 'string' && m.id.startsWith('seed-')) ||
          isFabricatedContact(m.senderId) ||
          isFabricatedContact(m.recipientId))
      ),
  );
  return { messages: kept, removed: messages.length - kept.length };
}

export interface PurgeReport {
  messagesRemoved: number;
  sessionsRemoved: number;
}

type StorageLike = {
  get: (key: string, fallback: any) => any;
  set: (key: string, value: any) => void;
};

/**
 * Strip fabricated entries from persisted state. Safe to call on every start:
 * it only writes when something was actually removed.
 */
export function purgeFabricatedStorage(
  storage: StorageLike = Utils.storage as StorageLike,
): PurgeReport {
  const report: PurgeReport = { messagesRemoved: 0, sessionsRemoved: 0 };
  try {
    const history = storage.get(STORAGE_KEYS.chatHistory, null);
    if (Array.isArray(history)) {
      const { messages, removed } = purgeFabricatedMessages(history);
      if (removed) {
        storage.set(STORAGE_KEYS.chatHistory, messages);
        report.messagesRemoved = removed;
      }
    }
    const sessions = storage.get(STORAGE_KEYS.openSessions, null);
    if (Array.isArray(sessions)) {
      const real = sessions.filter(
        (s: any) => s && !isFabricatedContact(s.contactId, s.contactName),
      );
      if (real.length !== sessions.length) {
        storage.set(STORAGE_KEYS.openSessions, real);
        report.sessionsRemoved = sessions.length - real.length;
      }
    }
  } catch {
    // Storage may be unavailable (private mode, quota); there is nothing to purge then.
  }
  return report;
}
