/**
 * Data tables for the RLV implementation (`rlv.ts`), taken from Firestorm's RLVa source
 * (`indra/newview/rlvhelper.cpp`: `RlvBehaviourDictionary`; `skins/default/xui/en/rlva_strings.xml`).
 * RLVa is (c) Kitty Barnett, LGPL 2.1. See docs/rlv.md for what is and is not implemented.
 *
 * `types` says which command forms exist: `add` (`@name=n|y`), `force`, `reply`. `strict` marks
 * behaviours that accept the `_sec` suffix. `option` is how the `:option` part is read for the add form.
 */

export type RlvOptionKind =
  'none' | 'exception' | 'noneOrException' | 'modifier' | 'noneOrModifier' | 'custom';
export interface RlvBehaviourInfo {
  types: Array<'add' | 'force' | 'reply'>;
  strict?: boolean;
  option?: RlvOptionKind;
  deprecated?: boolean;
}

export const RLV_BEHAVIOURS: Readonly<Record<string, RlvBehaviourInfo>> = {
  acceptpermission: { types: ['add'], option: 'none' },
  accepttp: { types: ['add'], strict: true, option: 'noneOrException' },
  accepttprequest: { types: ['add'], strict: true, option: 'noneOrException' },
  addattach: { types: ['add'], option: 'custom' },
  addoutfit: { types: ['add', 'force'], option: 'custom' },
  addoutfitall: { types: ['force'] },
  addoutfitallover: { types: ['force'] },
  addoutfitallthis: { types: ['force'] },
  addoutfitallthisover: { types: ['force'] },
  addoutfitover: { types: ['force'] },
  addoutfitthis: { types: ['force'] },
  addoutfitthisover: { types: ['force'] },
  adjustheight: { types: ['force'] },
  allowidle: { types: ['add'], option: 'none' },
  alwaysrun: { types: ['add'], option: 'none' },
  attach: { types: ['force'] },
  attachall: { types: ['force'] },
  attachallover: { types: ['force'] },
  attachalloverorreplace: { types: ['force'] },
  attachallthis: { types: ['add', 'force'], option: 'custom' },
  attachallthis_except: { types: ['add'], option: 'custom' },
  attachallthisover: { types: ['force'] },
  attachallthisoverorreplace: { types: ['force'] },
  attachover: { types: ['force'] },
  attachoverorreplace: { types: ['force'] },
  attachthis: { types: ['add', 'force'], option: 'custom' },
  attachthis_except: { types: ['add'], option: 'custom' },
  attachthisover: { types: ['force'] },
  attachthisoverorreplace: { types: ['force'] },
  buy: { types: ['add'], option: 'none' },
  camavdist: { types: ['add'], option: 'modifier', deprecated: true },
  camdistmax: { types: ['add'], option: 'modifier', deprecated: true },
  camdistmin: { types: ['add'], option: 'modifier', deprecated: true },
  camtextures: { types: ['add'], option: 'noneOrModifier', deprecated: true },
  camunlock: { types: ['add'], option: 'none', deprecated: true },
  camzoommax: { types: ['add'], option: 'custom', deprecated: true },
  camzoommin: { types: ['add'], option: 'custom', deprecated: true },
  chatnormal: { types: ['add'], option: 'none' },
  chatshout: { types: ['add'], option: 'none' },
  chatwhisper: { types: ['add'], option: 'none' },
  detach: { types: ['add', 'force'], option: 'custom' },
  detachall: { types: ['force'] },
  detachallthis: { types: ['add', 'force'], option: 'custom' },
  detachallthis_except: { types: ['add'], option: 'custom' },
  detachme: { types: ['force'] },
  detachthis: { types: ['add', 'force'], option: 'custom' },
  detachthis_except: { types: ['add'], option: 'custom' },
  edit: { types: ['add'], option: 'noneOrException' },
  editattach: { types: ['add'], option: 'none' },
  editobj: { types: ['add'], option: 'exception' },
  editworld: { types: ['add'], option: 'none' },
  emote: { types: ['add'], option: 'none' },
  fartouch: { types: ['add'], option: 'noneOrModifier' },
  findfolder: { types: ['reply'] },
  findfolders: { types: ['reply'] },
  fly: { types: ['add', 'force'], option: 'none' },
  getaddattachnames: { types: ['reply'] },
  getaddoutfitnames: { types: ['reply'] },
  getattach: { types: ['reply'] },
  getattachnames: { types: ['reply'] },
  getcam_avdist: { types: ['reply'] },
  getcam_avdistmax: { types: ['reply'] },
  getcam_avdistmin: { types: ['reply'] },
  getcam_fov: { types: ['reply'] },
  getcam_fovmax: { types: ['reply'] },
  getcam_fovmin: { types: ['reply'] },
  getcam_textures: { types: ['reply'] },
  getcommand: { types: ['reply'] },
  getgroup: { types: ['reply'] },
  getheightoffset: { types: ['reply'] },
  getinv: { types: ['reply'] },
  getinvworn: { types: ['reply'] },
  getoutfit: { types: ['reply'] },
  getoutfitnames: { types: ['reply'] },
  getpath: { types: ['reply'] },
  getpathnew: { types: ['reply'] },
  getremattachnames: { types: ['reply'] },
  getremoutfitnames: { types: ['reply'] },
  getsitid: { types: ['reply'] },
  getstatus: { types: ['reply'] },
  getstatusall: { types: ['reply'] },
  interact: { types: ['add'], option: 'none' },
  jump: { types: ['add'], option: 'none' },
  notify: { types: ['add'], option: 'custom' },
  pay: { types: ['add'], option: 'none' },
  permissive: { types: ['add'], option: 'none' },
  recvchat: { types: ['add'], strict: true, option: 'noneOrException' },
  recvchatfrom: { types: ['add'], strict: true, option: 'exception' },
  recvemote: { types: ['add'], strict: true, option: 'noneOrException' },
  recvemotefrom: { types: ['add'], strict: true, option: 'exception' },
  recvim: { types: ['add'], strict: true, option: 'custom' },
  recvimfrom: { types: ['add'], strict: true, option: 'exception' },
  redirchat: { types: ['add'], option: 'custom' },
  rediremote: { types: ['add'], option: 'custom' },
  remattach: { types: ['add', 'force'], option: 'custom' },
  remoutfit: { types: ['add', 'force'], option: 'custom' },
  rez: { types: ['add'], option: 'none' },
  sendchannel: { types: ['add'], strict: true, option: 'custom' },
  sendchannel_except: { types: ['add'], strict: true, option: 'custom' },
  sendchat: { types: ['add'], option: 'none' },
  sendgesture: { types: ['add'], option: 'none' },
  sendim: { types: ['add'], strict: true, option: 'custom' },
  sendimto: { types: ['add'], strict: true, option: 'exception' },
  setcam: { types: ['add'], option: 'none' },
  setcam_avdist: { types: ['add'], option: 'modifier' },
  setcam_avdistmax: { types: ['add'], option: 'modifier' },
  setcam_avdistmin: { types: ['add'], option: 'modifier' },
  setcam_eyeoffset: { types: ['add', 'force'], option: 'modifier' },
  setcam_eyeoffsetscale: { types: ['add', 'force'], option: 'modifier' },
  setcam_focus: { types: ['force'] },
  setcam_focusoffset: { types: ['add', 'force'], option: 'modifier' },
  setcam_fov: { types: ['force'] },
  setcam_fovmax: { types: ['add'], option: 'custom' },
  setcam_fovmin: { types: ['add'], option: 'custom' },
  setcam_mode: { types: ['force'] },
  setcam_mouselook: { types: ['add'], option: 'none' },
  setcam_origindistmax: { types: ['add'], option: 'modifier' },
  setcam_origindistmin: { types: ['add'], option: 'modifier' },
  setcam_textures: { types: ['add'], option: 'noneOrModifier' },
  setcam_unlock: { types: ['add'], option: 'none' },
  setdebug: { types: ['add'], option: 'none' },
  setoverlay: { types: ['add', 'force'], option: 'custom' },
  setsphere: { types: ['add', 'force'], option: 'custom' },
  setenv: { types: ['add'], option: 'none' },
  setgroup: { types: ['add', 'force'], option: 'none' },
  setoverlay_touch: { types: ['add'], option: 'custom' },
  setoverlay_tween: { types: ['force'] },
  share: { types: ['add'], strict: true, option: 'noneOrException' },
  sharedunwear: { types: ['add'], option: 'custom' },
  sharedwear: { types: ['add'], option: 'custom' },
  showhovertext: { types: ['add'], option: 'noneOrException' },
  showhovertextall: { types: ['add'], option: 'none' },
  showhovertexthud: { types: ['add'], option: 'none' },
  showhovertextworld: { types: ['add'], option: 'none' },
  showinv: { types: ['add'], option: 'none' },
  showloc: { types: ['add'], option: 'none' },
  showminimap: { types: ['add'], option: 'none' },
  shownames: { types: ['add'], strict: true, option: 'noneOrException' },
  shownametags: { types: ['add'], strict: true, option: 'custom' },
  shownearby: { types: ['add'], option: 'none' },
  showself: { types: ['add'], option: 'none' },
  showselfhead: { types: ['add'], option: 'none' },
  showworldmap: { types: ['add'], option: 'none' },
  sit: { types: ['add', 'force'], option: 'none' },
  sitground: { types: ['force'] },
  sittp: { types: ['add'], option: 'noneOrModifier' },
  standtp: { types: ['add'], option: 'none' },
  startim: { types: ['add'], strict: true, option: 'custom' },
  startimto: { types: ['add'], strict: true, option: 'exception' },
  temprun: { types: ['add'], option: 'none' },
  touchall: { types: ['add'], option: 'none' },
  touchattach: { types: ['add'], option: 'noneOrException' },
  touchattachother: { types: ['add'], option: 'noneOrException' },
  touchattachself: { types: ['add'], option: 'none' },
  touchfar: { types: ['add'], option: 'noneOrModifier' },
  touchhud: { types: ['add'], option: 'noneOrException' },
  touchme: { types: ['add'], option: 'none' },
  touchthis: { types: ['add'], option: 'exception' },
  touchworld: { types: ['add'], option: 'noneOrException' },
  tplm: { types: ['add'], option: 'none' },
  tploc: { types: ['add'], option: 'none' },
  tplocal: { types: ['add'], option: 'noneOrModifier' },
  tplure: { types: ['add'], strict: true, option: 'noneOrException' },
  tprequest: { types: ['add'], strict: true, option: 'noneOrException' },
  tpto: { types: ['force'] },
  unsharedunwear: { types: ['add'], option: 'custom' },
  unsharedwear: { types: ['add'], option: 'custom' },
  unsit: { types: ['add', 'force'], option: 'none' },
  version: { types: ['reply'] },
  versionnew: { types: ['reply'] },
  versionnum: { types: ['reply'] },
  viewnote: { types: ['add'], option: 'none' },
  viewscript: { types: ['add'], option: 'none' },
  viewtexture: { types: ['add'], option: 'none' },
  viewtransparent: { types: ['add'], option: 'none' },
  viewwireframe: { types: ['add'], option: 'none' },
};

/** `rlva_strings.xml` `anonyms`: what a hidden name is replaced with. */
/** Names that are synonyms of another behaviour (`BHVR_SYNONYM`): the restriction is held under the target name. */
export const RLV_SYNONYMS: Readonly<Record<string, string>> = {
  camavdist: 'setcam_avdist',
  camdistmin: 'setcam_avdistmin',
  camdistmax: 'setcam_avdistmax',
  camtextures: 'setcam_textures',
  camunlock: 'setcam_unlock',
  touchfar: 'fartouch',
};

export const RLV_ANONYMS: readonly string[] = [
  'A resident',
  'This resident',
  'That resident',
  'An individual',
  'This individual',
  'That individual',
  'A person',
  'This person',
  'That person',
  'A stranger',
  'This stranger',
  'That stranger',
  'A being',
  'This being',
  'That being',
  'An agent',
  'This agent',
  'That agent',
  'A soul',
  'This soul',
  'That soul',
  'Somebody',
  'Some people',
  'Someone',
  'Mysterious one',
  'An unknown being',
  'Unidentified one',
  'An unknown person',
];

/** Strings from `rlva_strings.xml` used by the handler (English). */
export const RLV_STRINGS = {
  hiddenGeneric: '(Hidden)',
  hiddenParcel: '(Hidden parcel)',
  hiddenRegion: '(Hidden region)',
  blockedRecvIm: '*** IM blocked by your viewer',
  blockedSendIm: "*** IM blocked by sender's viewer",
  blockedRecvImRemote:
    'The Resident you messaged is currently prevented from reading your instant messages at the moment, please try again later.',
  blockedTpLureRequestRemote:
    'The Resident is currently prevented from accepting. Please try again later.',
  blockedGeneric: 'Unable to perform action due to RLV restrictions',
  blockedTeleport: 'Unable to initiate teleport due to RLV restrictions',
  blockedStartIm: 'Unable to start IM session with [RECIPIENT] due to RLV restrictions',
  blockedNearby: 'Unable to see the presence of nearby avatars due to RLV restrictions',
  blockedScriptDialog: 'Unable to show script dialog or textbox due to RLV restrictions',
} as const;
