import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const jsonPath = path.resolve(__dirname, "../src/tokens/tokens.json");
const tsOutputPath = path.resolve(__dirname, "../src/tokens/tokens.ts");
const kotlinOutputPath = path.resolve(
  __dirname,
  "../../../Linkpoint/src/main/java/com/linkpoint/ui/components/linkpoint2/tokens/GeneratedTokens.kt"
);

function toPascalCase(str) {
  if (!str) return "";
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function toKotlinColor(hex) {
  if (!hex || typeof hex !== "string") return `Color(0xFF000000)`;
  const clean = hex.replace("#", "").trim();
  if (clean.length === 6) {
    return `Color(0xFF${clean.toUpperCase()})`;
  } else if (clean.length === 8) {
    const rr = clean.substring(0, 2);
    const gg = clean.substring(2, 4);
    const bb = clean.substring(4, 6);
    const aa = clean.substring(6, 8);
    return `Color(0x${aa.toUpperCase()}${rr.toUpperCase()}${gg.toUpperCase()}${bb.toUpperCase()})`;
  }
  return `Color(0xFF000000)`;
}

function generateTsBody(obj, indentLevel = 1) {
  const indent = "  ".repeat(indentLevel);
  let lines = [];

  for (const [key, val] of Object.entries(obj)) {
    if (val && typeof val === "object" && !("value" in val)) {
      lines.push(`${indent}${key}: {`);
      lines.push(generateTsBody(val, indentLevel + 1));
      lines.push(`${indent}},`);
    } else if (val && typeof val === "object" && "value" in val) {
      lines.push(`${indent}${key}: "${val.value}",`);
    }
  }

  return lines.join("\n");
}

function generateKotlinBody(obj, indentLevel = 1) {
  const indent = "    ".repeat(indentLevel);
  let lines = [];

  for (const [key, val] of Object.entries(obj)) {
    const pascalKey = toPascalCase(key);
    if (val && typeof val === "object" && !("value" in val)) {
      lines.push(`${indent}object ${pascalKey} {`);
      lines.push(generateKotlinBody(val, indentLevel + 1));
      lines.push(`${indent}}`);
    } else if (val && typeof val === "object" && "value" in val) {
      const colorVal = toKotlinColor(val.value);
      lines.push(`${indent}val ${pascalKey} = ${colorVal}`);
    }
  }

  return lines.join("\n");
}

export function generateTokens() {
  const rawData = fs.readFileSync(jsonPath, "utf-8");
  const tokenData = JSON.parse(rawData);

  const tsContent = `/**
 * Generated Design Tokens from tokens.json.
 * DO NOT EDIT DIRECTLY. Generated by packages/design-system/scripts/generate-tokens.js
 */

export const GENERATED_TOKENS = {
${generateTsBody(tokenData, 1)}
} as const;

export type GeneratedTokens = typeof GENERATED_TOKENS;
`;

  const kotlinContent = `package com.linkpoint.ui.components.linkpoint2.tokens

import androidx.compose.ui.graphics.Color

/**
 * Generated Design Tokens from tokens.json.
 * DO NOT EDIT DIRECTLY. Generated by packages/design-system/scripts/generate-tokens.js
 */
object GeneratedTokens {
${generateKotlinBody(tokenData, 1)}
}
`;

  fs.mkdirSync(path.dirname(tsOutputPath), { recursive: true });
  fs.writeFileSync(tsOutputPath, tsContent, "utf-8");
  console.log(`Generated TypeScript tokens at: ${tsOutputPath}`);

  fs.mkdirSync(path.dirname(kotlinOutputPath), { recursive: true });
  fs.writeFileSync(kotlinOutputPath, kotlinContent, "utf-8");
  console.log(`Generated Kotlin tokens at: ${kotlinOutputPath}`);
}

// Execute when run directly
if (process.argv[1] && process.argv[1].endsWith("generate-tokens.js")) {
  generateTokens();
}
