import {
  PALETTES as SYSTEM_PALETTES,
  PALETTE_FAMILIES as SYSTEM_PALETTE_FAMILIES,
} from '@linkpoint/design-system/tokens';

export const LEGACY_PALETTES = SYSTEM_PALETTES;
export const PALETTES = SYSTEM_PALETTES;
export const FAMILIES = SYSTEM_PALETTE_FAMILIES;
